import { NextRequest, NextResponse } from 'next/server';
import {
  checkOllamaStatus,
  ollamaDraftGenerate,
  getModelForTask,
} from '@/lib/ollamaProvider';
import { DRAFT_TEMPLATES, type DraftParams } from '@/lib/legalData';

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  const t0 = Date.now();
  try {
    const body = await req.json();
    const {
      draft_type = 'Bail Application (BNSS Sec 480)',
      petitioner_name = 'Applicant',
      respondent_name = 'State',
      facts = '',
      court_name = 'Sessions Court',
      sections_invoked = [],
    } = body;

    const secList = Array.isArray(sections_invoked) ? sections_invoked : [sections_invoked];
    const date = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });

    // Check Ollama availability
    const status = await checkOllamaStatus();

    let content: string;
    let engine: string;

    if (status.connected) {
      // Use Ollama for AI-powered draft generation
      const model = getModelForTask('draft', status.models);
      content = await ollamaDraftGenerate(
        draft_type,
        petitioner_name,
        respondent_name,
        facts,
        secList,
        court_name,
        model
      );
      engine = `Ollama/${model} (AI-Generated)`;
    } else {
      // Fallback to embedded templates
      const params: DraftParams = {
        petitioner_name,
        respondent_name,
        facts,
        court_name,
        sections_list: secList.join(', ') || 'BNSS § 480',
        date,
      };
      const templateFn = DRAFT_TEMPLATES[draft_type] ?? DRAFT_TEMPLATES['Bail Application (BNSS Sec 480)'];
      content = templateFn(params);
      engine = 'Embedded-Template (Ollama offline)';
    }

    return NextResponse.json({
      id: Math.random().toString(36).slice(2),
      title: `${draft_type} Draft`,
      draft_type,
      generated_content: content,
      sections_cited: secList,
      word_count: content.split(/\s+/).length,
      disclaimer: 'Generated by LegalAI Platform. Mandatory review by qualified Advocate required before filing in any court.',
      generated_at: new Date().toISOString(),
      response_time_ms: Date.now() - t0,
      engine,
      ollama_status: status.connected ? 'CONNECTED' : 'OFFLINE',
    });
  } catch (e: unknown) {
    return NextResponse.json({ error: (e as Error)?.message ?? String(e) }, { status: 500 });
  }
}
