events {
    worker_connections 1024;
}

http {
    upstream frontend_app {
        server frontend:3000;
    }

    upstream backend_api {
        server backend-api:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /docs {
            proxy_pass http://backend_api/docs;
            proxy_set_header Host $host;
        }
    }
}
